#!/bin/bash
# Test Installation on New Machine
# This script simulates the exact error you got

echo "🧪 Testing BondoMVC v1.2.0 Installation"
echo "========================================"
echo ""
echo "1. Creating project from Packagist..."
echo "   $ composer create-project bondomvc/mvc test-install"
echo ""
echo "2. After composer finishes, run:"
echo "   $ cd test-install"
echo "   $ cp .env.example .env"
echo "   $ nano .env  (edit DB credentials)"
echo "   $ php check-installation.php"
echo ""
echo "3. Expected output:"
echo "   ✅ PHP 8.0+"
echo "   ✅ All directories present"
echo "   ✅ Composer installed"
echo "   ✅ .env exists"
echo "   ✅ Database connected (if DB configured)"
echo "   ✅ All directories writable"
echo "   ✅ All key files present"
echo "   ✅ All extensions loaded"
echo ""
echo "4. Then run:"
echo "   $ php artisan serve"
echo ""
echo "5. Visit: http://localhost:8000"
echo ""
echo "If you still see the 'use' error, it means Packagist hasn't"
echo "updated yet. You can force update:"
echo "   1. Go to https://packagist.org/packages/bondomvc/mvc"
echo "   2. Click 'Update' button"
echo "   3. Wait 5 minutes"
echo "   4. Try again"
echo ""
